version: '3.8'

services:

  postgres:
    image: postgres:14.7-alpine3.17
    container_name: nik-niklist-server-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: niklist

  maildev:
    image: maildev/maildev
    container_name: nik-niklist-server-maildev
    ports:
      - "1080:1080"
      - "1025:1025"
